# Generated by Django 3.0.5 on 2020-05-02 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lang_learning', '0004_userlanguage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlanguage',
            unique_together={('language', 'user')},
        ),
    ]
