# Generated by Django 3.0.5 on 2021-01-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_learning', '0007_word_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
