# Generated by Django 3.0.5 on 2021-01-31 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('lang_learning', '0008_userlanguage_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguage',
            name='active',
        ),
        migrations.CreateModel(
            name='UserActiveLanguage',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang_learning.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
