# Generated by Django 3.0.5 on 2021-01-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_learning', '0009_auto_20210131_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UserActiveLanguage',
        ),
    ]
