# Generated by Django 3.0.5 on 2021-02-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_learning', '0010_auto_20210131_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguage',
            name='active',
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
